export enum ERROR_CODES {
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  GROUP_ALREADY_EXISTS = 'GROUP_ALREADY_EXISTS',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
  SORT_NOT_FOUND = 'SORT_NOT_FOUND',
  SORT_ALREADY_EXISTS = 'SORT_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PLANTATION_NOT_FOUND = 'PLANTATION_NOT_FOUND',
  PLANTATION_ALREADY_EXISTS = 'PLANTATION_ALREADY_EXISTS',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
export const ERROR_MESSAGES = {
  [ERROR_CODES.UNAUTHORIZED]: 'Неверный логин или пароль',
  [ERROR_CODES.USER_NOT_FOUND]: 'Неверный логин или пароль',
  [ERROR_CODES.GROUP_NOT_FOUND]: 'Группа не существует',
  [ERROR_CODES.GROUP_ALREADY_EXISTS]: 'Группа уже существует',
  [ERROR_CODES.CATEGORY_NOT_FOUND]: 'Категория не существует',
  [ERROR_CODES.CATEGORY_ALREADY_EXISTS]: 'Категория уже существует',
  [ERROR_CODES.SORT_NOT_FOUND]: 'Сорт не существует',
  [ERROR_CODES.SORT_ALREADY_EXISTS]: 'Сорт уже существует',
  [ERROR_CODES.PLANTATION_NOT_FOUND]: ' Плантация не существует',
  [ERROR_CODES.PLANTATION_ALREADY_EXISTS]: 'Плантация уже существует',
};
