export enum ERROR_CODES {
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  GROUP_ALREADY_EXISTS = 'GROUP_ALREADY_EXISTS',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
}
export const ERROR_MESSAGES = {
  [ERROR_CODES.GROUP_NOT_FOUND]: 'Группа не существует',
  [ERROR_CODES.GROUP_ALREADY_EXISTS]: 'Группа уже существует',
  [ERROR_CODES.CATEGORY_NOT_FOUND]: 'Категория не существует',
  [ERROR_CODES.CATEGORY_ALREADY_EXISTS]: 'Категория уже существует',
};
